### ISSUE TITLE
Sparkplug website re-design

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/sparkplug.eclipse.org#42]
Current mock up:
https://sparkplug-working-group.webflow.io/

**Comment by ericpoirier** [comment]
# Tasks 

### UPDATES
 - October 29, 2020 - @chrisguindon - List task update based off the sparkplug website sync meeting with @fdesbiens and @Ioana240 
- November 18, 2020 - @ericpoirier - Added new tasks to list after the meeting we had today.

## Header

- [x] Need a transparent png for the Logo 
- [x] The image will need to be lighter to be more accessible (Eric)
- [x] The grey button will need to be darker for accessibility reasons (Eric)
- [x] Remove main menu links and use the CTA for Join Us (Eric)
- [ ] Add social Media links based on design decided by Brian and Clark (Eric)

## Testimonials

- [x] There are two different sections on the home page (Eric)
  - [x] The first testimonial at the top of the page will be static and from Arlen Nipper (Eric)
  - [x] Testimonial section at the bottom of the page will require a carousel. (Eric)
- [ ] Provide testimonials pictures (Ioana)

## Content

- [ ] Validate with the designer that we have proper permission to use all the graphics from the design (Ioana)
  - [x] Background image in the header https://deploy-preview-45--eclipsefdn-sparkplug.netlify.app/images/jumbotron-image.jpg?e392a1df3035ba6bf6ba4b567e36b785
  - [x] Icons such as, but not limited to: https://deploy-preview-45--eclipsefdn-sparkplug.netlify.app/images/sparkplug/diagrams/single-source-of-truth.png
  - [x] Book https://deploy-preview-45--eclipsefdn-sparkplug.netlify.app/images/sparkplug/book/guide.jpg
  - [ ] 1-2-3 icons: https://deploy-preview-45--eclipsefdn-sparkplug.netlify.app/images/sparkplug/join/step1.png
  - [x] News icons: https://deploy-preview-45--eclipsefdn-sparkplug.netlify.app/images/sparkplug/resources/icon1.png
    - [x] We will need a unique icon for community news, announcements, and resources

## Join Us section

- [x] Replicate as-is from mockup (Eric)

## Book section

- [x] Build it as-is, the image might change. The document is not ready yet. (Eric)
- [ ] Frederic will provide new content for this section (Frédéric)

## Contact form

- [x] Meet Us should link to the sparkplug mailing-list  (Eric)
- [ ] Discuss with karen in order to create an hubspot form for the page similar to https://outreach.eclipse.foundation/eclipse-iot-developer-survey-2020 (Ioana)
- [x] Remove form and just add a Download Now button that links to external page containing the form (Eric)

## Recent News

- [x] Update news shortcode in order to support icons for each item (Eric)
- [x] Add upcoming event section under SPARKPLUG RESOURCES . You can use the timeline l&f from iot.eclipse.org (Eric)

## Resources

- [X] Ask WG if we need a separate page (Frédéric)
- [x] Create a resource page (Eric)
- [ ] Add Resources link to top menu (Eric)
- [ ] Add sidebar to Resources page (Eric)

## Compatibility page

It was decided that we would create a separate issue for the compatibility page. We can implement this page once the WG is closer to launching this initiative.

- [x] Create a separate GitHub issue for tracking the compatibility page (Eric)

## Footer

- [x] missing the Eclipse Footer (Eric)

**Comment by fdesbiens** [comment]
I discussed the website with the steering committee last week. You will find the answers to your questions below. Please feel free to ping me if you need additional details, @ericpoirier. 

> Header
> 
> * [ ]  Make sure we have rights to use the background image (Frédéric)

This background and the icons at the bottom of the page come from Shutterstock. I suppose we dont have the rights to them in the context of the Shutterstock license. What do you think? The committee is fine with us using something else.

> * [ ]  The image will need to be lighter to be more accessible (Eric)

The committee is not wedded to any particular shade for the colours used in the mockup. They asked us to fix any accessibility issue in any way we see fit.

> * [ ]  The grey button will need to be darker for accessibility reasons (Eric)
> 
> Testimonials
> 
> * [ ]  There are two different sections on the home page (Eric)
>   
>   * [ ]  The first testimonial at the top of the page will be static and from Arlen Nipper (Eric)

The committee confirmed this is what they want.

>   * [ ]  Testimonial section at the bottom of the page will require a carousel. (Eric)

The committee confirmed this is what they want.

> * [ ]  Provide testimonials pictures (Frédéric)

@Ioana240 will reach out to the authors of the testimonials and ask them for a suitable picture. Please attach the pictures to this issue, Ioana.

> 
> Content
> 
> * [ ]  Validate with designer that we have proper permission to use all the graphics from the design (Frédéric)

The diagrams in the middle have been built by committee members and can be used. The icons at the bottom are from Shutterstock. There is no need for us to replicate them exactly and we are free to use alternate designs if this is more practical for us.

> 
> Join Us section
> 
> * [ ]  Replicate as-is from mockup (Eric)
> 
> Book section
> 
> * [ ]  Build it as-is, the image might change. The document is not ready yet. (Eric)

For the time being, we will use this section to point people to our membership prospectus. 

> 
> Contact form
> 
> * [ ]  Meet Us -> link to Slack space ? (Eric)
>   
>   * [ ]    Provide link to Slack space (Frédéric)

Invite link: https://join.slack.com/t/eclipse-sparkplug-wg/shared_invite/zt-btcn48au-luMXPXMbMhBzS4pCaLO6_w

> * [ ]  Remove form and just add a Download Now button that links to external page containing the form (Eric)
> 
> Recent News

The committee was not aware of the distinction between events and news. They were not aware of Eclipse newsroom. They are fine to have events and news as distinct categories. Please propose a design.
 
> * [ ]  Validate with designer that we have proper permission to use all the graphics from the design (Frédéric)

They're also from Shutterstock. We can substitute our own.

> * [ ]  Come up with news categories for how to use the icons (Eric)
> 
> Resources
> 
> * [ ]  Ask WG if we need a separate page (Frédéric)

The committee stated is it OK to have the three most recent resources at the bottom of the home page and a separate page with the full list of resources.

> 
> Compatibility page
> 
> * [ ]  Discuss with karen in order to create an hubspot form for the page (Frederic)

I didn't have the time to cover that yet.

> * [ ]  Ask WG if we need a separate page, if so, we will need a mockup (Frederic)

We showed the Jakarta EE compatible products page to the committee and they are fine with that design. Please create one and keep it hidden for now.

> 
> Footer
> 
> * [ ]  missing the Eclipse Footer (Eric)

**Comment by chrisguindon** [comment]
@Ioana240

This is the preview url: https://deploy-preview-45--eclipsefdn-sparkplug.netlify.app/

**Comment by ericpoirier** [comment]
@chrisguindon 
"Meet Us should link to the sparkplug newsletter (Eric)"

Did you mean Mailing List instead of Newsletter here? If not, can you provide the link to the Sparkplug Newsletter?

Thanks.

**Comment by chrisguindon** [comment]
> @chrisguindon
> "Meet Us should link to the sparkplug newsletter (Eric)"
> 
> Did you mean Mailing List instead of Newsletter here? If not, can you provide the link to the Sparkplug Newsletter?
> 
> Thanks.

+1 It should say mailing-list. I made the edit to the list.

**Comment by ericpoirier** [comment]
I'm at a point where I need to create the "Resources" page. Is the idea a page similar to the Resources on Iot.eclipse.org?

**Comment by Ioana240** [comment]
Hi Eric,

We can create the "Resources" page similar to iot.eclipse.org. @fdesbiens could you please also share your input so that we are sure we are all aligned on this?

Thank you,
Ioana

**Comment by fdesbiens** [comment]
@ericpoirier @Ioana240 Yes, the IoT format is fine. Thanks!

**Comment by fdesbiens** [comment]
@ericpoirier @chrisguindon I confirm we cannot use the Shutterstock-licensed icons included in the original wireframe. We need to replace them.

**Comment by chrisguindon** [comment]
> @ericpoirier @chrisguindon I confirm we cannot use the Shutterstock-licensed icons included in the original wireframe. We need to replace them.

Thanks for letting us know! Did you or @Ioana240  engage with @karenmcnaughton  in order to help you update these assets?

**Comment by ericpoirier** [comment]
I added the Resources page and block to the redesign layout and I am also using Feather Icons for the News and resources items instead of icons that were provided.

https://github.com/EclipseFdn/sparkplug.eclipse.org/pull/45

**Comment by Ioana240** [comment]
Bio pictures are attached to this comment
![Dominik Obermeier](https://user-images.githubusercontent.com/61757816/100234725-cb8c4980-2f2b-11eb-9c77-070c60e87524.jpg)
![Jeff Knepper](https://user-images.githubusercontent.com/61757816/100234957-1312d580-2f2c-11eb-8b76-97a6a074bd5b.jpg)
![Todd Anslinger](https://user-images.githubusercontent.com/61757816/100235084-3d649300-2f2c-11eb-91a3-a744e173d41d.jpg)
![don-pearson (1) (1)](https://user-images.githubusercontent.com/61757816/100235193-58cf9e00-2f2c-11eb-9956-fce2bf2130b5.jpg)
![Arlen Nipper](https://user-images.githubusercontent.com/61757816/100236272-bca69680-2f2d-11eb-82d3-e7c8b3a30576.PNG)

**Comment by Ioana240** [comment]
Here is a document with new icons for the Sparkplug website that would replace the Shutterstock icons --> https://docs.google.com/document/d/1LuJ1zNM4a5h-1muog8nisScMG-6X5N-ePWwenI4RYCI/edit

Thank you!
Ioana

**Comment by ericpoirier** [comment]
> Bio pictures are attached to this comment
> ![Dominik Obermeier](https://user-images.githubusercontent.com/61757816/100234725-cb8c4980-2f2b-11eb-9c77-070c60e87524.jpg)
> ![Jeff Knepper](https://user-images.githubusercontent.com/61757816/100234957-1312d580-2f2c-11eb-8b76-97a6a074bd5b.jpg)
> ![Todd Anslinger](https://user-images.githubusercontent.com/61757816/100235084-3d649300-2f2c-11eb-91a3-a744e173d41d.jpg)
> ![don-pearson (1) (1)](https://user-images.githubusercontent.com/61757816/100235193-58cf9e00-2f2c-11eb-9956-fce2bf2130b5.jpg)
> ![Arlen Nipper](https://user-images.githubusercontent.com/61757816/100236272-bca69680-2f2d-11eb-82d3-e7c8b3a30576.PNG)

Are those pictures for the Testimonials section?

**Comment by ericpoirier** [comment]
> Here is a document with new icons for the Sparkplug website that would replace the Shutterstock icons --> https://docs.google.com/document/d/1LuJ1zNM4a5h-1muog8nisScMG-6X5N-ePWwenI4RYCI/edit
> 
> Thank you!
> Ioana

Hi Ioana,

Can you provide the images in PNG or SVG format?

Thanks.

**Comment by Ioana240** [comment]
Hi Eric,

Yes, the photos are for the testimonials section.
I will add tomorrow the images in one of those formats :)

Thanks!

**Comment by ericpoirier** [comment]
> Hi Eric,
> 
> Yes, the photos are for the testimonials section.
> I will add tomorrow the images in one of those formats :)
> 
> Thanks!

Not sure if I missed it, but did you provide the text for the testimonials?

**Comment by chrisguindon** [comment]
@Ioana240 These pictures seems to come from an external website... are you sure we have permissions to use them?

**Comment by Ioana240** [comment]
@chrisguindon  That's how the photos have been shared with me via emails. Some of them were sent previously when we had events and we used those. 

@ericpoirier There are some testimonials already added in the preview of the website https://deploy-preview-45--eclipsefdn-sparkplug.netlify.app/ Are there other testimonials that we should add and I am not aware of? @fdesbiens could you please advise on this? Thanks!

**Comment by ericpoirier** [comment]
@Ioana240 yes you're right, for some reason I thought those testimonials were placeholders.

Would it be possible for you to identify the pictures?

Thanks.

**Comment by Ioana240** [comment]
@ericpoirier  I named the pictures when I saved them but they don't seem to appear when I click again on the photo in GitHub. So here are the names enumerated after each picture attached to the bug:
1. Dominik Obermeier - HiveMQ
2. Jeff Knepper - Canary Labs
3. Todd Anslinger - Chevron
4. Don Pearson - Inductive Automation
5. Arlen Nipper - Cirrus Link
Thanks!

**Comment by ericpoirier** [comment]
> @ericpoirier I named the pictures when I saved them but they don't seem to appear when I click again on the photo in GitHub. So here are the names enumerated after each picture attached to the bug:
> 
>     1. Dominik Obermeier - HiveMQ
> 
>     2. Jeff Knepper - Canary Labs
> 
>     3. Todd Anslinger - Chevron
> 
>     4. Don Pearson - Inductive Automation
> 
>     5. Arlen Nipper - Cirrus Link
>        Thanks!

Ok thanks!

**Comment by Ioana240** [comment]
Hi @ericpoirier,

Here are the icons in png format:

1. Single source of truth
![computing-cloud](https://user-images.githubusercontent.com/61757816/100879802-2d106300-34ac-11eb-89ee-1a32559a623d.png)
2. Decoupled data
![settings](https://user-images.githubusercontent.com/61757816/100879870-474a4100-34ac-11eb-84f5-6c625a017f8a.png)
3. Immediate discovery
![reminder (1)](https://user-images.githubusercontent.com/61757816/100879943-6648d300-34ac-11eb-9652-ad7f20183710.png)
4. Inherited security
![security](https://user-images.githubusercontent.com/61757816/100879989-782a7600-34ac-11eb-9e4d-8bbaadd3a613.png)
5. State awareness
![healthcare](https://user-images.githubusercontent.com/61757816/100880372-ec651980-34ac-11eb-8fd5-15ca3c991dd1.png)

Thanks!

**Comment by ericpoirier** [comment]
Thanks Ioana for providing those graphic elements.

Quick question for the first testimonials block on the home page. Should this always be the same testimonials or should it be different every time the page loads?

Thanks.

**Comment by Ioana240** [comment]
@ericpoirier 

I suggest the testimonials should be different every time the page loads.

Thanks!

**Comment by ericpoirier** [comment]
I updated the staging page with the latest changes.

https://deploy-preview-45--eclipsefdn-sparkplug.netlify.app/

I also made the First testimonials block dynamic so that a random testimonial show up at every page load. 

Note that in the testimonials section, we are still missing one picture for Angus Shih and the logo is showing up. I didn't spend time to fix what the logo looks like because I'm expecting a picture soom for that person but let me know if where are going to be using the logo instead.

Thanks.

**Comment by ericpoirier** [comment]
@Ioana240 we are still missing the following graphic elements to complete this website's redesign:

- The book
- Picture of Angus Shih
- The background image in the header (not sure if we have rights to use it, please validate)

Thanks.

**Comment by Ioana240** [comment]
@ericpoirier We have a few more updates on this website:

- I am waiting for Angus Shih's bio photo, will keep you posted in the bug when it is available

- Regarding the  "book" section: we will replace that book with the Eclipse Sparkplug Membership Prospectus (Mehrnaz created the design which I have attached in the bug. Please replace "Learn how Eclipse Sparkplug and MQTT technology can transform your IIoT project with this free resource." with "Learn more about the key benefits of the Eclipse Sparkplug membership and how you can contribute to the Sparkplug working group"
<img width="751" alt="33" src="https://user-images.githubusercontent.com/61757816/101502117-dd7cdc00-3970-11eb-8a58-ac6da69d34bb.png">


- For the background header image, the same, Mehrnaz created the design, I  uploaded the final version in the bug
<img width="1254" alt="2" src="https://user-images.githubusercontent.com/61757816/101502040-c342fe00-3970-11eb-966b-d800f4a08538.png">


-In the header section, please delete "Join Us" button, we should only have the "Learn more" button

- In the "How to join the working group section" section, instead of the "Meet Us" button that leads to the mailing list, please add a "Meet us on Slack" button with the link here:https://app.slack.com/client/TSU5P680K/learning-slack, and a "Sign up for our Mailing List" button with the link here: https://accounts.eclipse.org/mailing-list/sparkplug-wg

- Below the "How to join the working group section", please delete the content "Already familiar with the group?
Download the membership guide with application to get started" and the "download now" button

-For the "Sparkplug Resources" section, in the buttom section of the website, please add the following resources:
1. **Video**
"Sparkplug Has Launched! Now What?", May 2020, https://youtu.be/MrRYKZX-D0g

"MQTT Sparkplug Specification", December 2019, https://inductiveautomation.com/resources/video/mqtt-sparkplug-specification

2. **Articles**
MQTT Sparkplug essentials part 1: https://www.hivemq.com/blog/mqtt-sparkplug-essentials-part-1-introduction/ (Dominik Obermaier, HiveMQ)

MQTT Sparkplug essentials part 2: https://www.hivemq.com/blog/sparkplug-essentials-part-2-architecture/ ( (Dominik Obermaier, HiveMQ))

MQTT Sparkplug: Edge driven, report by exception, best-in-class IIoT https://blog.canarylabs.com/get-started-with-mqtt-sparkplug (Jeff Knepper, Canary Labs)

3. **Podcast**
IoT For All Podcast — "Building MQTT and its Role in IIoT" https://www.iotforall.com/podcasts/e072-mqtt-arlen-nipper (Arlen Nipper, Cirrus Link Solutions)

Thank you!
Ioana

**Comment by meKokabi** [comment]
Here is the header background image ![SparkPlugHome](https://user-images.githubusercontent.com/75500459/101530788-5e7fa780-3960-11eb-9d89-962607882872.png)
Here is the book image ![bigstock-Grey-Tablet-With-Empty-White-S-299150248](https://user-images.githubusercontent.com/75500459/101530819-650e1f00-3960-11eb-96a7-9eaa67bcd54e.png)

**Comment by ericpoirier** [comment]
Hi @Ioana240 and @meKokabi,

Thanks for providing the updated elements for this.

I made all the changes you both asked for but here are items that are still missing:

Learn more button in jumbotron doesn't have a link
Download button next to the book doesn't have a link
Testimonial picture for Angus Shih

Other then that, let me know if I missed anything.

https://deploy-preview-45--eclipsefdn-sparkplug.netlify.app/

Thanks.

**Comment by Ioana240** [comment]
Hi @ericpoirier,
The preview looks nice!

- For the learn more button in the jumbotron, please use this link https://sparkplug.eclipse.org/about/faq/

- For the download button next to the book, please add this link: https://f.hubspotusercontent10.net/hubfs/5413615/sparkplug-member-prospectus%202020.pdf

- Angus Shih still hasn't replied to my email regarding the bio photo, we will probably update that photo afterwards

- We still need to change the 1-2-3 icons in the "how to join the working group" section, Mehrnaz is currently creating the mockups for this, I will update the bug when the icons are available

Thank you!

**Comment by ericpoirier** [comment]
Hi @Ioana240,

I made the updates you mentioned in your last comment.

https://deploy-preview-45--eclipsefdn-sparkplug.netlify.app/

All that should be missing now is the 1-2-3 icons.

**Comment by meKokabi** [comment]
HI Eric,
Thanks for your help and update! I just post the icons on Github!
Thanks again,
Mehrnaz

**Comment by meKokabi** [comment]
![NumberIcons](https://user-images.githubusercontent.com/75500459/101783272-0e235980-3ac8-11eb-94e2-ad0aa9b52e45.png)
Here You Are! The number icons!

**Comment by ericpoirier** [comment]
Hi @meKokabi,

Thanks for providing the images. I updated the staging page.

https://deploy-preview-45--eclipsefdn-sparkplug.netlify.app/

@Ioana240, now that all is missing is the picture for Angus, when can we go live with this redesign?

Thanks.

**Comment by meKokabi** [comment]
Hi @ericpoirier 
My big apologies for asking you to redoing the icons, as clark just asked for one more edits, so this is the new one! Sorry again!
![NumberIcons copy](https://user-images.githubusercontent.com/75500459/101796198-b17b6b00-3ad6-11eb-9efd-c231285c86ac.png)

**Comment by ericpoirier** [comment]
Hi @meKokabi 
No problem, I updated the staging page with the updated icons.

Let me know if there's something else.

Thanks.

**Comment by Ioana240** [comment]
Hi @ericpoirier , the page looks good! We don't have further edits or suggestions. I will update the bug with regard to when we can go live with the website.

Thank you!

**Comment by croundy** [comment]
@ericpoirier site is looking great! A couple of minor nits:

1. Membership Prospectus--remove 2nd "the" so it reads as follows: Learn more about the key benefits of Eclipse Sparkplug membership and how you can contribute to the Sparkplug working group

Also, please flow the text so the word "group" is not left alone on its own line

2. Sparkplug Resources section: Assuming we will turn the headlines of each of those resources into hyperlinks? 

Thanks again for all your help and great work!

**Comment by croundy** [comment]
@ericpoirier if we can get these last minor changes made, I think we will be ready to declare victory and get this live. Can we make that happen by tomorrow? Thanks for all your help!

**Comment by ericpoirier** [comment]
Hi @croundy,

I made the updates and they are now on staging.

https://deploy-preview-45--eclipsefdn-sparkplug.netlify.app/

Let me know if there's anything else.

Thanks.

**Comment by croundy** [comment]
@ericpoirier looks great! I'm good with going live with this unless @fdesbiens knows of any reasons to hold off.

**Comment by fdesbiens** [comment]
@ericpoirier @croundy Looks good to me. Release the Kraken!

**Comment by croundy** [comment]
@ericpoirier please let @fdesbiens and I know once this is live so we can advise the Sparkplug WG. thanks again for all your help!

**Comment by ericpoirier** [comment]
Hi @croundy,

I'm waiting for @chrisguindon to review the changes that was made for this project. Once that's done, we will push this live.

**Comment by croundy** [comment]
@ericpoirier @chrisguindon thanks again to both of you! I know how pleased the Sparkplug WG members will be!
